@startuml entityManager

allowmixing

left to right direction

file "logger.ts" as loggerTs #LightCyan {
    object logger
}

file "entityManager.ts" as entityManagerTs #Cyan {
    interface Email
    interface User
    object config
    cloud EntityManager

    Email --> EntityManager
    User --> EntityManager
    config --> EntityManager
    logger --> EntityManager

    interface EmailItem
    interface UserItem
    object entityManager

    EntityManager --> EmailItem: exports
    EntityManager --> UserItem: exports
    EntityManager --> entityManager: exports

    UserItem -[hidden] EmailItem
    entityManager -[hidden] UserItem
}

@enduml