@startuml entityClient

allowmixing

left to right direction

file "logger.ts" as loggerTs #LightCyan {
    object errorLogger
}

file "entityClient.ts" as entityClientTs #cyan {
    object options
    class EntityClient

    errorLogger --o EntityClient
    options --* EntityClient

    object entityClient

    EntityClient --> entityClient: exports
}

@enduml