@startuml entityManager

allowmixing

left to right direction

file "entityManager.ts" as entityManagerTs {
    interface Email
    interface User
    object config
    cloud EntityManager

    Email --> EntityManager
    User --> EntityManager
    config --> EntityManager

    interface EmailItem
    interface UserItem
    object entityManager

    EntityManager --> EmailItem: exports
    EntityManager --> UserItem: exports
    EntityManager --> entityManager: exports

    UserItem -[hidden] EmailItem
    entityManager -[hidden] UserItem
}

@enduml