@startuml handler

allowmixing

left to right direction

file "logger.ts" as loggerTs {
    object logger
}

file "entityManager.ts" as entityManagerTs {
    interface UserItem
    object entityManager
}

file "entityClient.ts" as entitClientTs {
    object entityClient

    logger --* entityClient 
}

file "user-search.ts" as searchTs {
    object handler

    entityManager --* handler  
    UserItem --* handler 
    handler *-- entityClient
    entityManager *-- logger

    object shardQueryMapBuilder
    shardQueryMapBuilder -o handler
}

@enduml