@startuml handler

allowmixing

left to right direction

database DynamoDB
object params

file "logger.ts" as loggerTs #LightCyan {
    object logger
}

file "entityManager.ts" as entityManagerTs #LightCyan {
    interface User
    interface UserItem
    object entityManager
}

file "entityClient.ts" as entitClientTs #LightCyan {
    object entityClient
}

file "user-handler.ts" as searchTs #Cyan {
    object handler

    handler <- params
    User <|.. params 
    UserItem <|.. handler 
    entityManager --o handler  
    entityClient --o handler
    logger -o handler
    handler <--> DynamoDB
    entityClient -[hidden]- logger

    object shardQueryMapBuilder
    handler o-- shardQueryMapBuilder
}

@enduml